# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['server/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('shared', 'shared'),
        ('legal', 'legal'),
    ],
    hiddenimports=[
        'server',
        'server.main',
        'server.routes',
        'server.routes.auth',
        'server.routes.chat',
        'server.routes.calls',
        'server.routes.files',
        'server.routes.forward',
        'server.routes.legal',
        'server.routes.contacts_groups',
        'server.routes.p2p',
        'server.routes.ipfs',
        'server.routes.bookmarks',
        'server.routes.pins',
        'server.routes.stats',
        'server.routes.audit',
        'server.routes.federation',
        'server.ws',
        'server.ws.chat_manager',
        'server.ws.notifications',
        'server.ws.p2p_manager',
        'server.ws.signaling',
        'server.core',
        'server.core.database',
        'server.core.models',
        'server.core.security',
        'server.core.storage',
        'server.core.federation',
        'server.core.ipfs_client',
        'server.core.ipfs_manager',
        'server.utils',
        'server.utils.file_cleanup',
        'server.utils.logger',
        'shared',
        'shared.config',
        'shared.schemas',
        'shared.constants',
        'shared.rate_limiter',
        'pydantic',
        'pydantic_settings',
        'sqlalchemy',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'starlette',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'starlette.websockets',
        'nacl',
        'nacl.signing',
        'nacl.encoding',
        'jose',
        'jose.jwt',
        'jose.constants',
        'bcrypt',
        'httpx',
        'websockets',
        'slowapi',
        'apscheduler',
        'prometheus_client',
        'psutil',
        'qrcode',
        'PIL',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'unittest', 'test', 'distutils', 'setuptools',
        'matplotlib', 'numpy', 'pandas', 'scipy',
        'pytest', '_pytest', 'pygments', 'IPython', 'notebook',
        'sphinx', 'cv2', 'torch', 'tensorflow',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=['libcrypto-3.dll', 'libssl-3.dll', 'python312.dll'],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
