# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['server/main.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('shared', 'shared'),
    ],
    hiddenimports=[
        'server.core.models',
        'server.core.database',
        'server.core.security',
        'server.core.storage',
        'server.core.audit',
        'server.core.ipfs_manager',
        'server.ws.chat_manager',
        'server.ws.signaling',
        'server.ws.p2p_manager',
        'server.ws.notifications',
        'server.routes.auth',
        'server.routes.chat',
        'server.routes.calls',
        'server.routes.files',
        'server.routes.forward',
        'server.routes.legal',
        'server.routes.contacts_groups',
        'server.routes.p2p',
        'server.routes.ipfs',
        'server.routes.bookmarks',
        'server.routes.pins',
        'server.routes.stats',
        'server.routes.audit',
        'server.utils.file_cleanup',
        'server.utils.logger',
        'shared.config',
        'shared.schemas',
        'shared.constants',
        'shared.rate_limiter',
        'shared.exceptions',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='nurchat-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
)
