name : Ollama Config
version: 1.0.0
models:
  - name: "Qwen 2.5 Coder 1.5B (Local)"
    provider: ollama
    model: "qwen2.5-coder:1.5b"

tabAutocompleteModel:
  name: "Qwen 2.5 Coder 1.5B (Local)"
  provider: ollama
  model: "qwen2.5-coder:1.5b"
